import type { Provider } from "@/src/domain/models";

const createdAt = "2026-07-23T12:00:00.000Z";

export const BUILT_IN_PROVIDERS: Provider[] = [
  {
    providerId: "provider_research",
    name: "Research Brief Agent",
    slug: "research-brief-agent",
    description:
      "Synthesises supplied or seeded sources into a focused, evidence-labelled research brief.",
    capabilities: ["research-brief", "competitor-research", "synthesis"],
    inputSchema: {
      type: "object",
      required: ["topic", "researchQuestion"],
    },
    outputSchema: {
      type: "object",
      required: [
        "executiveSummary",
        "keyFindings",
        "evidence",
        "uncertainties",
        "sources",
        "recommendedNextSteps",
      ],
    },
    pricingModel: "FLAT",
    basePrice: "1.20",
    supportedTokens: ["USDC"],
    supportedChains: ["goat-testnet"],
    endpoint: "/api/providers/provider_research",
    x402Enabled: false,
    erc8004AgentId: null,
    erc8004Registry: null,
    payoutAddress: "0x1111111111111111111111111111111111111111",
    averageRating: 4.8,
    completedJobs: 184,
    failedJobs: 7,
    averageCompletionTime: 42,
    active: true,
    source: "BUILT_IN",
    verificationStatus: "LOCAL_PROFILE",
    createdAt,
    updatedAt: createdAt,
  },
  {
    providerId: "provider_website",
    name: "Website Audit Agent",
    slug: "website-audit-agent",
    description:
      "Reviews observable page structure and positioning without executing page scripts.",
    capabilities: ["website-audit", "positioning-analysis", "competitor-research"],
    inputSchema: {
      type: "object",
      required: ["url", "targetAudience", "auditGoal"],
    },
    outputSchema: {
      type: "object",
      required: [
        "requestedUrl",
        "positioningSummary",
        "strengths",
        "weaknesses",
        "missingInformation",
        "recommendations",
        "priorities",
        "observedChecks",
      ],
    },
    pricingModel: "PER_URL",
    basePrice: "0.85",
    supportedTokens: ["USDC"],
    supportedChains: ["goat-testnet"],
    endpoint: "/api/providers/provider_website",
    x402Enabled: false,
    erc8004AgentId: null,
    erc8004Registry: null,
    payoutAddress: "0x2222222222222222222222222222222222222222",
    averageRating: 4.7,
    completedJobs: 263,
    failedJobs: 11,
    averageCompletionTime: 28,
    active: true,
    source: "BUILT_IN",
    verificationStatus: "LOCAL_PROFILE",
    createdAt,
    updatedAt: createdAt,
  },
  {
    providerId: "provider_web3",
    name: "Web3 Basic Risk Agent",
    slug: "web3-basic-risk-agent",
    description:
      "Produces a scoped, fact-separated wallet or contract risk overview; it is not a security audit.",
    capabilities: ["web3-basic-risk", "address-check", "contract-overview"],
    inputSchema: {
      type: "object",
      required: ["network", "address", "desiredChecks"],
    },
    outputSchema: {
      type: "object",
      required: [
        "network",
        "address",
        "riskOverview",
        "observedFacts",
        "warnings",
        "confidence",
        "manualChecks",
        "disclaimer",
      ],
    },
    pricingModel: "PER_CHECK",
    basePrice: "1.10",
    supportedTokens: ["USDC"],
    supportedChains: ["goat-testnet"],
    endpoint: "/api/providers/provider_web3",
    x402Enabled: false,
    erc8004AgentId: null,
    erc8004Registry: null,
    payoutAddress: "0x3333333333333333333333333333333333333333",
    averageRating: 4.6,
    completedJobs: 96,
    failedJobs: 5,
    averageCompletionTime: 36,
    active: true,
    source: "BUILT_IN",
    verificationStatus: "LOCAL_PROFILE",
    createdAt,
    updatedAt: createdAt,
  },
  {
    providerId: "provider_budget_audit",
    name: "Budget Page Scanner",
    slug: "budget-page-scanner",
    description:
      "A low-cost local comparison provider with limited positioning coverage.",
    capabilities: ["website-audit"],
    inputSchema: { type: "object" },
    outputSchema: { type: "object" },
    pricingModel: "PER_URL",
    basePrice: "0.55",
    supportedTokens: ["USDC"],
    supportedChains: ["goat-testnet"],
    endpoint: "/api/providers/provider_budget_audit",
    x402Enabled: false,
    erc8004AgentId: null,
    erc8004Registry: null,
    payoutAddress: "0x4444444444444444444444444444444444444444",
    averageRating: 2.1,
    completedJobs: 22,
    failedJobs: 18,
    averageCompletionTime: 65,
    active: true,
    source: "LOCAL",
    verificationStatus: "LOCAL_PROFILE",
    createdAt,
    updatedAt: createdAt,
  },
  {
    providerId: "provider_alt_research",
    name: "Signal Synthesis Lab",
    slug: "signal-synthesis-lab",
    description:
      "Local fallback profile for structured research synthesis and evidence tables.",
    capabilities: ["research-brief", "competitor-research"],
    inputSchema: { type: "object" },
    outputSchema: { type: "object" },
    pricingModel: "FLAT",
    basePrice: "1.35",
    supportedTokens: ["USDC"],
    supportedChains: ["goat-testnet"],
    endpoint: "/api/providers/provider_alt_research",
    x402Enabled: false,
    erc8004AgentId: null,
    erc8004Registry: null,
    payoutAddress: "0x5555555555555555555555555555555555555555",
    averageRating: 4.3,
    completedJobs: 78,
    failedJobs: 8,
    averageCompletionTime: 50,
    active: true,
    source: "LOCAL",
    verificationStatus: "LOCAL_PROFILE",
    createdAt,
    updatedAt: createdAt,
  },
];
